### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Sentero-esp12** [MattMoony/figaro#21]
**Describe the bug**
Getting error when running `./gui.sh`

**To Reproduce**
Steps to reproduce the behaviour:
1. Installed via `./setup.sh`
2. Ran `python figaro.py -s`. In `choose length` I entered `512`
3. Ran `./gui.sh`
4. Getting this error

**Expected behaviour**
GUI should open

**Screenshots**
![image](https://user-images.githubusercontent.com/35060206/120225060-3c9b1980-c24d-11eb-956d-dc38d4521c70.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1 (Ubuntu 20.04)
 - Node v14.17.0
 - Python: 3.8.8

**Comment by mm12** [comment]
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn /usr/bin/env python3 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by MattMoony** [comment]
Really sorry, because I don't have the time to fix the issue at the moment, but I know what the problem is.
I have yet to decide on the smartest way to run the appropriate version of python3 in this first _alpha release_... ^^ Platform-dependent builds will definitely make life easier later on.

However, if you want to fix your issue right now, before I have the time to introduce the fix into the repository, just update [line 22 in figaro/gui/src/main.ts](https://github.com/MattMoony/figaro/blob/master/figaro/gui/src/main.ts#L22) - replace `/usr/bin/env python3` with the command that runs Python 3 on your platform.

Hope to find the time to fix this soon - Matthias

**Comment by MattMoony** [comment]
_Edit:_ As it turns out, I was simply a bit lost... I took another look at the issue today and realized that I was already using `/usr/bin/env python3` in the setup scripts... so, why should it work there and not here? Well... obviously I didn't split the argument (`python3`) from the path to the binary (`/usr/bin/env`) causing node to interpret it as a path to `"/usr/bin/env python3"` - a file that obviously doesn't exist ... 🤦 

After commit 1491d5c, the issue shouldn't arise anymore...
