### ISSUE TITLE
GUI with no components on Windows

### ISSUE THREAD

**Issue by marchingon12** [MattMoony/figaro#29]
**Describe the bug**
After running '\gui.ps1', script runs without problems but the GUI just shows a blank page with no components. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run \gui.ps1 in terminal
2. Wait for GUI window to pop up
3. See error

**Expected behaviour**
Open the GUI as shown in the README on GitHub.

**Screenshots**
![WindowsTerminal_uxsIMnk95K](https://user-images.githubusercontent.com/41235480/123542624-2ee88f00-d73a-11eb-8f92-9b6d50514d7a.png)
![electron_6cfOx32aGP](https://user-images.githubusercontent.com/41235480/123542642-4758a980-d73a-11eb-974d-7d841d309ccf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Additional context**
CLI works fine with no problems.

**Comment by MattMoony** [comment]
Hi, 

this is because of the way I changed the development behaviour of the GUI in 63ae305c2bd59685173d0d6e98a190e5429d721a. Now, if you use `.\gui.ps1` to launch the GUI, i.e. if you launch the GUI in development mode, it will try to load the page from `http://localhost:8000` - the port where the Gatsby development build would be running.

If you don't mean to work on Figaro in terms of developing something new, it's probably best, if you just tried using the **Windows installer** from the [last release](https://github.com/MattMoony/figaro/releases/tag/v0.3-alpha) as this problem shouldn't arise there.

**Comment by marchingon12** [comment]
I see! Thank you very much for the speedy answer. As you said, the installer works flawlessly, and now I understand the reason why it looked the way it was before - for development purposes. Also I just wanted to say I appreciate your work on this project! Great work!
